### ISSUE TITLE
Website links megathread

### ISSUE THREAD

**Issue by bcardarella** [lumen/getlumen.org#1]
Please post in here

**Comment by lawik** [comment]
Keynote ElixirConf 2019: https://www.youtube.com/watch?v=uMgTIlgYB-U

Repository: https://github.com/lumen/lumen

Code Mesh, Paul, talk: https://youtu.be/PBY8MQ09D9w

Lone Star 2020, Luke: https://youtu.be/I_2H16ZM824

Elixir Wizards, podcast episode: https://smartlogic.io/podcast/elixir-wizards/s3e11-lumen/

Still need to find Elixir Talk episode.

**Comment by duggiefresh** [comment]
The `Docs: Lumen Examples` link on the main page is broken. 

<img width="550" alt="Screen Shot 2020-09-01 at 12 34 34 PM" src="https://user-images.githubusercontent.com/1206678/91897706-89ff4180-ec4f-11ea-89a5-dde7b19fbc29.png">

Is it supposed to link to https://github.com/lumen/examples?

**Comment by lawik** [comment]
Thanks, yes, will fix.

(someone moved it ; )

(also, fixed)
